site_name: "NOAMI Documentation"
site_author: Alex Post
site_description: >-
  C++ Library for Astrodynamics Simulation and Experimentation

# Repository
repo_name: naomi
repo_url: https://github.com/apost71/naomi

# Copyright
copyright: Copyright © 2024 Alex Post

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: slate
      primary: pink
      accent: pink

plugins:
  - search
  - mkdoxy:
      projects:
        naomi:
          src-dirs: include
          full-doc: True
#          template-dir: templates-custom
          doxy-cfg-file: Doxyfile
#          doxy-cfg:
#            FILE_PATTERNS: "*.py"
#            EXAMPLE_PATH: ""
#            RECURSIVE: True
#            OPTIMIZE_OUTPUT_JAVA: True
#            JAVADOC_AUTOBRIEF: True
#            EXTRACT_ALL: True
      save-api: .mkdoxy
      full-doc: True
      debug: False
      ignore-errors: False
      emojis-enabled: True

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - def_list
  - toc:
      permalink: True
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - markdown.extensions.md_in_html
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.blocks.admonition:
      types:
        - new
        - settings
        - note
        - abstract
        - info
        - tip
        - success
        - question
        - warning
        - failure
        - danger
        - bug
        - example
        - quote
  - pymdownx.blocks.details:
  - pymdownx.blocks.html:
  - pymdownx.blocks.definition:
  - pymdownx.blocks.tab:
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home:
      - pages/index.md
  - Usage:
      - pages/index.md
      - Basic Usage: pages/basic_usage.md
      - Advanced Usage: pages/propagation.md

  - API Reference:
      - "Links": "naomi/links.md"
      - "Classes":
          - "Class List": "naomi/annotated.md"
          - "Class Index": "naomi/classes.md"
          - "Class Hierarchy": "naomi/hierarchy.md"
          - "Class Members": "naomi/class_members.md"
          - "Class Member Functions": "naomi/class_member_functions.md"
          - "Class Member Variables": "naomi/class_member_variables.md"
          - "Class Member Typedefs": "naomi/class_member_typedefs.md"
          - "Class Member Enumerations": "naomi/class_member_enums.md"
      - "Namespaces":
          - "Namespace List": "naomi/namespaces.md"
          - "Namespace Members": "naomi/namespace_members.md"
          - "Namespace Member Functions": "naomi/namespace_member_functions.md"
          - "Namespace Member Variables": "naomi/namespace_member_variables.md"
          - "Namespace Member Typedefs": "naomi/namespace_member_typedefs.md"
          - "Namespace Member Enumerations": "naomi/namespace_member_enums.md"
      - "Functions": "naomi/functions.md"
      - "Variables": "naomi/variables.md"
      - "Macros": "naomi/macros.md"
      - "Files": "naomi/files.md"