name: Naomi CI
on:
  push:
    branches:
      - main

jobs:
  run-tests:
    name: Test Project
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2022
          - ubuntu-22.04
          - macos-12
        compiler:
          - llvm
          - gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: 'true'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            /usr/local/lib
          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
          restore-keys: |
            ${{ runner.os }}-${{ env.BUILD_TYPE }}-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          cppcheck: true
          clangtidy: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfmt-dev libeigen3-dev libboost-all-dev libopenblas-dev \
              liblapack-dev libarpack2-dev libsuperlu-dev libarmadillo-dev
          
          sudo apt-get install libgmp-dev libflint-dev libmpc-dev libomp-dev llvm
          cd symengine
          mkdir build && cd build
          cmake -DWITH_GMP=on -DWITH_MPFR=on -DWITH_MPC=on -DINTEGER_CLASS=flint -DWITH_LLVM=on -DWITH_SYMENGINE_THREAD_SAFE=on -DWITH_OPENMP=on ..    make
          sudo make install
      

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0