name: Naomi CI
on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
      - include/**
      - .github/workflows/ci.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04
        compiler:
          - gcc
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: 'true'

#      - name: Cache
#        uses: actions/cache@v3
#        with:
#          path: |
#            /usr/local/lib
#          key: ${{ runner.os }}-${{ matrix.compiler }}-${{ env.BUILD_TYPE }}-${{ hashFiles('**/CMakeLists.txt') }}-${{ hashFiles('./vcpkg.json')}}
#          restore-keys: |
#            ${{ runner.os }}-${{ env.BUILD_TYPE }}-

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: ${{ matrix.compiler }}
          cmake: true
          ninja: true
          cppcheck: true
          clangtidy: true

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v2
        with:
          cmake-version: '3.25.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libfmt-dev libeigen3-dev libboost-all-dev libopenblas-dev \
              liblapack-dev libarpack2-dev libsuperlu-dev libarmadillo-dev libgtest-dev
          
          sudo apt-get install libgmp-dev libflint-dev libmpc-dev libomp-dev llvm
#          cd symengine
#          mkdir build && cd build
#          cmake -DWITH_GMP=on -DWITH_MPFR=on -DWITH_MPC=on -DINTEGER_CLASS=flint -DWITH_LLVM=on -DWITH_SYMENGINE_THREAD_SAFE=on -DWITH_OPENMP=on ..
#          sudo make -j 2
#          sudo make install

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: "${{ runner.os }}-${{ matrix.compiler }}-${{ hashFiles('**/CMakeLists.txt') }}"  # Eg. "some_build-ubuntu-latest"

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          source-dir: symengine
          options: CMAKE_INSTALL_PREFIX=/home/runner/work/ CMAKE_C_COMPILER_LAUNCHER=ccache CMAKE_CXX_COMPILER_LAUNCHER=ccache WITH_GMP=on WITH_MPFR=on WITH_MPC=on INTEGER_CLASS=flint WITH_LLVM=on WITH_SYMENGINE_THREAD_SAFE=on WITH_OPENMP=on
          build-args: "--target install"


      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
          options: CMAKE_INSTALL_PREFIX="/home/runner/work/;/usr/bin/local/" CMAKE_C_COMPILER_LAUNCHER=ccache CMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
        with:
          test-dir: "build/tests"
          tests-regex: "TestKeplerian.*"